POST http://localhost:18080/api/bookmarks HTTP/1.1
content-type: application/json

{
    "title": "momo",
    "url": "Wed, 21 Oct 2015 18:27:50 GMT",
    "description": "le livre du siecle"
}

#######

GET http://localhost:18080/api/bookmarks HTTP/1.1

#######

GET http://localhost:18080/api/bookmarks?query=toto HTTP/1.1